apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  labels:
    app: hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: sampleapplication
        image: vinuinstinct123/helloworld
        ports: 
        - containerPort: 5001
---        
apiVersion: v1
kind: Service
metadata:
  name: helloworldservice
  labels:
    app: hello
spec:
  type: LoadBalancer
  selector:
    app: hello
  ports:
    - protocol: TCP
      port: 80         # The port that will be exposed externally
      targetPort: 5001 # The port on the container where the service forwards traffic

